### ISSUE TITLE
apt install nvidia-cudnn libcublaslt12 libcublas12 unable to locate packages

### ISSUE THREAD

**Issue by drtechfuchs** [loeeeee/immich-in-lxc#12]
I am trying to follow your instructions in a debian CT, however

apt install nvidia-cudnn libcublaslt12 libcublas12

doesn't seem to work, what repository do I need to add for these?

**Comment by makovez** [comment]
You are probably installing the repo in a non-ubuntu distro. I had the same issue in debian 12.  I have installed cudnn and cuda toolkit from official nvidia site install instructions, because those packages (nvidia-cudnn libcublaslt12 libcublas12) are not in debian repo.

Just follow these instructions:
- https://developer.nvidia.com/cudnn-downloads
- https://developer.nvidia.com/cuda-downloads

**Comment by loeeeee** [comment]
> You are probably installing the repo in a non-ubuntu distro. I had the same issue in debian 12. I have installed cudnn and cuda toolkit from official nvidia site install instructions, because those packages (nvidia-cudnn libcublaslt12 libcublas12) are not in debian repo.
> 
> Just follow these instructions:
> 
> * https://developer.nvidia.com/cudnn-downloads
> * https://developer.nvidia.com/cuda-downloads

Thanks for your comments.

I have updated the Readme, and installation on Debian is now a bit more clear.

**Comment by loeeeee** [comment]
If any issues are encountered, you are welcome to reopen the issue. 😃 @drtechfuchs
