### ISSUE TITLE
Install script fails if PROXY_POETRY is empty

### ISSUE THREAD

**Issue by Sab44** [loeeeee/immich-in-lxc#2]
First of all, thanks for putting this guide together, really appreciated!

As the title says, if PROXY_POETRY is not set the install script will fail saying "-i  flag requires a parameter" (something along those lines, I don't have the exact message available any more).

Checking the `install.sh` script I adapted line 210
```
pip3 install poetry -i $PROXY_POETRY
```
to
```
pip3 install poetry
```
which fixed my case without a proxy configured.

Some minor additonal things I noticed during installation (LXC with Debian 12):
- `add-apt-repository universe` in the FFMPEG setup did not work for me - `Unable to handle repository shortcut 'universe'` but apparently this was not important as I could simply continue.
- there are 2 `sudo` commands in the FFMPEG setup which I had to remove, as I was already running as root and it complained that it couldn't find a `sudo` command.

In the end I got it working with these changes. Thanks again.

**Comment by loeeeee** [comment]
Hi, Sab44!

Thanks a lot for the detailed feedback!

> As the title says, if PROXY_POETRY is not set the install script will fail saying "-i flag requires a parameter" (something along those lines, I don't have the exact message available any more).

Oooops. I never tested it w/o the proxy server. It is now fixed and defaults to pypi server. 9829d94a9343f97c9cea2b4328b62098c0937b94

> `add-apt-repository universe` in the FFMPEG setup did not work for me - Unable to handle repository shortcut `'universe'` but apparently this was not important as I could simply continue.

Oooops again. I added additional explanation in the README. It is because Debian needs some slightly different command to add the repo than Ubuntu or its derivative. e17b5b5423dc5b1c9ec12ae64b74c46bbd484aa7

> there are 2 `sudo` commands in the FFMPEG setup which I had to remove, as I was already running as root and it complained that it couldn't find a `sudo` command.

Ha. I did not thought of that. `Debian` does not come with `sudo` installed, and for a LXC environment, removing these `sudo` makes way more sense! 06711c9947c929ff0d35a072a3d3a0736d4ac2e9
