### ISSUE TITLE
Immich thumbnails fail to generate -- missing icc_transform class

### ISSUE THREAD

**Issue by ahmadhadidi** [loeeeee/immich-in-lxc#48]
Hi @loeeeee

I've been successful in installing Immich, I realized the problem with the mount points last week, I was supposed to mount them first before starting with the instructions in the guide.

After using Immich, non of the images/videos are generating videos, examining the `/var/log/immich/web.log` file contains this (and many similar errors but with different IDs).. could it be something that was not installing correctly?

``` bash
[Nest] 82270  - 10/22/2024, 2:58:30 PM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsOperation: class "icc_transform" not found
VipsOperation: class "jpegsave" not found
[Nest] 82270  - 10/22/2024, 2:58:30 PM   ERROR [Microservices:JobService] Error: VipsOperation: class "icc_transform" not found
VipsOperation: class "jpegsave" not found
    at Sharp.toFile (/home/immich/app/node_modules/sharp/lib/output.js:90:19)
    at MediaRepository.generateThumbnail (/home/immich/app/dist/repositories/media.repository.js:65:14)
    at MediaService.generateImageThumbnails (/home/immich/app/dist/services/media.service.js:157:38)
    at async MediaService.handleGenerateThumbnails (/home/immich/app/dist/services/media.service.js:101:25)
    at async /home/immich/app/dist/services/job.service.js:163:36
    at async Worker.processJob (/home/immich/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/home/immich/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 82270  - 10/22/2024, 2:58:30 PM   ERROR [Microservices:JobService] Object:
{
  "id": "293dc9b4-5527-41ec-800d-95e0592074d4"  # this ID.
}
```

If this is beyond the scope of this project please let me know.

**Comment by loeeeee** [comment]
Hi @ahmadhadidi ,

Sorry about delayed reply.

Unfortunately, recently, I need to work on some important university things, and thus, cannot work on the project. I promise I will be back in several weeks.

Sorry about not being able to solve the issue right now

**Comment by ahmadhadidi** [comment]
Hi @loeeeee, it's all good.

Perhaps you could point me to where you suspect that it could have caused this and I can try fixing it?

**Comment by vhsdream** [comment]
Getting the same error on a freshly built Ubuntu 24.04 LXC. I also noticed that there is a build failure when I run the pre-install script. It's early in the script, during the JPEGXL build, it gets to about 80% and instead of failing out and exiting the script it just jumps to the next task. 

![JXL](https://github.com/user-attachments/assets/6c62a7b9-5c9a-4d0a-b291-eea5ecd2f39e)

Also, before this the output suggests that 'OpenEXR' and 'gdk-pixbuf-2.0' are missing, but I'm not sure if that means anything at all.

**Comment by loeeeee** [comment]
> Getting the same error on a freshly built Ubuntu 24.04 LXC. I also noticed that there is a build failure when I run the pre-install script. It's early in the script, during the JPEGXL build, it gets to about 80% and instead of failing out and exiting the script it just jumps to the next task.

Right now, I have disabled the building of libjxl, because of all the issues people have encountered. Rerun the `dep-ubuntu.sh` and `pre-install.sh` should do.

As of my understanding, the immich base-image builds libjxl with some hack, by installing some dev package first, and later forcefully remove it, which is not a good idea for a persistent LXC deployment.

I have been working on building the libjxl for a while, but it is quite tricky. 😢 I will come back to this issue when I am free in couple of weeks. 😃 

> Also, before this the output suggests that 'OpenEXR' and 'gdk-pixbuf-2.0' are missing, but I'm not sure if that means anything at all.

I do not think official immich image installed them as well, but maybe their base-image come with it as standard, and they do not have to install it. Nonetheless, these packages are included in the dependency scripts now.

**Comment by loeeeee** [comment]
> Hi @loeeeee, it's all good.
> 
> Perhaps you could point me to where you suspect that it could have caused this and I can try fixing it?

Well, can you try building the immich without libjxl, i.e., using the latest main branch? I believe it has something to do with libjxl trying to install the libjpeg with API version 80 instead of 62, while Immich uses version 62. However, this is just a guess.

**Comment by vhsdream** [comment]
OK just re-did all the scripts from the repo and I have a thumbnail, and the image opens just fine now:

![image](https://github.com/user-attachments/assets/87d0b242-8b16-4f10-acc9-9b30e11883fb)

So you must have been on to something.

**Comment by loeeeee** [comment]
> OK just re-did all the scripts from the repo and I have a thumbnail, and the image opens just fine now:

Glad to hear that! 😺

**Comment by ahmadhadidi** [comment]
Hi @loeeeee I just reran the scripts on a fresh new install and now I can see the thumbnails and the images. Ich danke dir 😊.

**Comment by loeeeee** [comment]
> Hi @loeeeee I just reran the scripts on a fresh new install and now I can see the thumbnails and the images. Ich danke dir 😊.

Glad to hear that! Bitte 😃
