### ISSUE TITLE
[Question] Immich Config for Intel/OpenVINO ML Setup

### ISSUE THREAD

**Issue by DammersH** [loeeeee/immich-in-lxc#58]
Hey guys

thanks a lot for the work you have done so far. 

I was wondering regarding this bit for the setup

> Because we are install Immich instance in a none docker environment, some DNS lookup will not work. For instance, we need to change the URL inside Administration > Settings > Machine Learning Settings > URL to http://localhost:2283, otherwise the web server cannot communicate with the ML backend.

Since the ML Server is listening on 3003 (at least what the log says) I couldn't understand why the 2283 port, since this is the webinterface (if I understood it correctly).

And just a small shot in the dark, do you know someone who got ML up and running under a Debian 12 setup with intel quicksync?

**Comment by loeeeee** [comment]
Thanks for pointing out the mistakes in the guide. Yes, it is indeed should be `localhost:3003` to communicate with ML backend, which is a very non-intelligent mistake made by me. 😵 It is now fixed in the guide.

Regarding Intel Quick Sync, I believe it is for video transcoding, and is not for hw-accelerated ML. If you install the jellyfin-ffmpeg, you will get quick-sync transcoding support out of box. However, you need to enable it in transcoding settings by selecting Quick-Sync or VAAPI, depending on your setup.

**Comment by loeeeee** [comment]
Regarding hw-accelerated ML, I believe what you are looking for is [OpenVINO](https://onnxruntime.ai/docs/execution-providers/OpenVINO-ExecutionProvider.html).

Immich does officially supports it. However, I can give a rough guide on how to enable it. I cannot go into details because I do not have time to really test and support this feature.

## Main Idea

Essentially, Immich ML component runs on ONNX-runtime, and it can be used on Quick-Sync machines. All we need to do is to install correct dependency. The following guide is not tested, but may worth a shot.

## Check ONNX-runtime support

The device running Onnx-runtime is referred to as an execution provider. One should firstly make sure their devices is supported.

## Install dependency

One will need to uncomment anything that is related to Intel in `dep-common.sh` and `dep-debian.sh`. After that, one should run `dep-debian.sh` to install all the needed dependency.

## Build Immich with correct flag

Find following part in `install.sh`,

```bash
# Install CUDA parts only when necessary
if [ $isCUDA = true ]; then
    poetry install --no-root --with dev --with cuda
else
    poetry install --no-root --with dev --with cpu
fi
```

Change it into,

```bash
poetry install --no-root --with dev --with openvino
```

## That is it

Yes, that is it. One should follow the rest of the guide as is. This, in theory, should enable hw-acceleration for ml on intel machines.

**Comment by DammersH** [comment]
I'm grateful that you gave me a guideline.

What I can report:
Installation of OpenVino  went smoothly and without any problems, I was able to start ./install.sh with your suggested changes.

From what I can see the CPU load went from 100% down to 25%-ish, intel-gpu-top doesen't show any load (don't know if it should at all).

**Comment by loeeeee** [comment]
> From what I can see the CPU load went from 100% down to 25%-ish, intel-gpu-top doesen't show any load (don't know if it should at all).

This is the part that I could not help with. Sorry about that. I do not have a testing machine with Intel CPU that has a working iGPU. 🫨 

No idea how to see if it works based on a quick Google. Soooo, let's assume it works. 😏

**Comment by DammersH** [comment]
Please don't worry, you gave me just the right pointers to investigate further.

Again thank you very much.

**Comment by loeeeee** [comment]
> Please don't worry, you gave me just the right pointers to investigate further.
> 
> Again thank you very much.

You are welcome! 😃
